import type { AppProps } from 'next/app';
import Head from 'next/head';

import '@/styles/fonts.css';
import { QueryClient, QueryClientProvider } from 'react-query';

import { GlobalStyle } from '@styles/global';

const queryClient = new QueryClient({
    defaultOptions: {
        queries: {
            staleTime: 5 * (60 * 1000), // 5 mins
            cacheTime: 10 * (60 * 1000), // 10 mins
        },
    },
});
export default function App({ Component, pageProps }: AppProps) {
    return (
        <>
            <Head>
                <title>uxstudio challenge</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <GlobalStyle />
            <QueryClientProvider client={queryClient}>
                <Component {...pageProps} />
            </QueryClientProvider>
        </>
    );
}
